"use client";

import { AlertCircle, BookOpen, CheckCircle2, Loader2, RotateCcw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { practiceAnswerCount, practiceScore, type TaylorPracticeFeedback } from "@/lib/taylor-practice";

export function TaylorPracticeFeedbackPanel({ feedback, onRetry }: {
  feedback: TaylorPracticeFeedback;
  onRetry: () => void;
}) {
  const score = practiceScore(feedback);
  const answerCount = practiceAnswerCount(feedback);
  if (feedback.status === "requesting_feedback") return <section className="mt-6 rounded-2xl border border-brand/20 bg-brand-light p-6" aria-label="Practice feedback"><div role="status" className="flex items-start gap-3"><Loader2 className="mt-0.5 h-5 w-5 shrink-0 animate-spin text-brand" /><div><h2 className="font-semibold text-text-primary">Preparing your practice feedback</h2><p className="mt-1 text-sm text-text-muted">Reviewing this conversation for specific ways to improve your answers.</p></div></div></section>;
  if (feedback.status === "insufficient_evidence") return <section className="mt-6 rounded-2xl border border-border bg-surface p-6" aria-label="Practice feedback"><div role="status" className="flex items-start gap-3"><BookOpen className="mt-0.5 h-5 w-5 shrink-0 text-brand" /><div><h2 className="font-semibold text-text-primary">A little more practice is needed</h2><p className="mt-2 text-sm leading-relaxed text-text-muted">{feedback.message || "There are not enough recorded answers to give useful feedback or a practice score. Try answering a few questions in your next session."}</p><p className="mt-2 text-xs text-text-muted">No practice score was assigned.</p></div></div></section>;
  if (feedback.status === "unavailable") return <section className="mt-6 rounded-2xl border border-border bg-surface p-6" aria-label="Practice feedback"><div role="alert" className="flex items-start gap-3"><AlertCircle className="mt-0.5 h-5 w-5 shrink-0 text-text-muted" /><div><h2 className="font-semibold text-text-primary">Feedback is unavailable right now</h2><p className="mt-2 text-sm leading-relaxed text-text-muted">{feedback.message || "Your practice has ended. You can check for saved feedback or start a new practice session."}</p><Button variant="secondary" size="sm" className="mt-4" onClick={onRetry}><RotateCcw className="h-3.5 w-3.5" />Check Saved Feedback</Button></div></div></section>;
  return <section className="mt-6 rounded-2xl border border-border bg-surface p-5 sm:p-8 shadow-sm" aria-label="Practice feedback">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><div className="mb-2 flex items-center gap-2 text-xs font-semibold text-brand"><CheckCircle2 className="h-4 w-4" />Practice complete</div><h2 className="text-xl font-bold text-text-primary">Your practice feedback</h2></div>{score !== null && <div className="rounded-xl border border-brand/20 bg-brand-light px-5 py-3 text-center"><p className="text-3xl font-bold text-brand">{score}<span className="text-sm font-medium text-text-muted"> / 100</span></p><p className="mt-1 text-xs text-text-muted">Indicative practice score</p></div>}</div>
    <p className="mt-3 text-xs leading-relaxed text-text-muted">Based only on this practice conversation. This is not an official interview score and does not change your application status.</p>
    {answerCount && <p className="mt-2 text-xs text-text-muted">{answerCount}</p>}
    {feedback.summary && <p className="mt-5 text-sm leading-relaxed text-text-primary">{feedback.summary}</p>}
    {Boolean(feedback.criteria?.length) && <div className="mt-6 grid gap-3 sm:grid-cols-3">{feedback.criteria!.map((criterion, index) => {
      const criterionScore = practiceScore({ status: "ready", indicative_score: criterion.score });
      return <div key={index} className="rounded-xl border border-border p-4"><h3 className="text-sm font-semibold capitalize text-text-primary">{criterion.name.replaceAll("_", " ")}</h3>{criterionScore !== null && <p className="mt-2 text-xl font-bold text-brand">{criterionScore}<span className="text-xs font-normal text-text-muted"> / 100</span></p>}<p className="mt-2 text-xs leading-relaxed text-text-muted">{criterion.reason}</p></div>;
    })}</div>}
    {Boolean(feedback.strengths?.length) && <div className="mt-6"><h3 className="font-semibold text-text-primary">What worked well</h3><ul className="mt-3 list-disc space-y-2 pl-5 text-sm leading-relaxed text-text-muted">{feedback.strengths!.map((strength, index) => <li key={index}>{strength}</li>)}</ul></div>}
    {Boolean(feedback.areas_to_improve?.length) && <div className="mt-6"><h3 className="font-semibold text-text-primary">What to work on next</h3><ul className="mt-3 list-disc space-y-2 pl-5 text-sm leading-relaxed text-text-muted">{feedback.areas_to_improve!.map((area, index) => <li key={index}>{area}</li>)}</ul></div>}
    {Boolean(feedback.better_answers?.length) && <div className="mt-6"><h3 className="font-semibold text-text-primary">Ways to strengthen your answers</h3><div className="mt-3 space-y-4">{feedback.better_answers!.map((answer, index) => <article key={index} className="rounded-xl border border-border bg-bg p-4"><h4 className="text-sm font-semibold text-text-primary">{answer.question}</h4>{answer.answer_excerpt && <blockquote className="mt-3 border-l-2 border-border pl-3 text-xs leading-relaxed text-text-muted"><span className="font-medium">From your answer: </span>{answer.answer_excerpt}</blockquote>}<p className="mt-3 text-xs font-semibold text-brand">{answer.example_kind === "template" ? "Answer template" : "Suggested answer"}</p>{answer.example_kind === "template" && <p className="mt-1 text-xs text-text-muted">Fill in brackets with details that are true of your own experience.</p>}<p className="mt-3 whitespace-pre-wrap text-sm leading-relaxed text-text-primary">{answer.example}</p>{answer.explanation && <p className="mt-3 text-xs leading-relaxed text-text-muted">{answer.explanation}</p>}</article>)}</div></div>}
  </section>;
}
